name:  Build, Test and upload coverage report

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          python3 -m pytest -v test/
      - name: Run test with coverage report and generate documentation
        run: |
          coverage run --source=. -m pytest && coverage xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: 56ba2a9a-8abc-4a62-82cc-20f66da78fa3